#+TITLE: Vlad dotemacs
#+AUTHOR: Vlad Tutunea
#+STARTUP: overview
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Dotemacs
Personal dotemacs configuration used mainly for programming and org mode.

Font Global Variables:
#+begin_src emacs-lisp

(defvar vt/default-font-size 140)
(defvar vt/default-variable-font-size 140)

;; Make frame transparency overridable
(defvar vt/frame-transparency '(90 . 90))

#+end_src

** Tips
Packages' documentation can be accessed by using =C-c C-o= or running =M-x org-open-at-point=

* Startup performance

#+begin_src emacs-lisp

;; The default is 800 kilobytes.  Measured in bytes.
(setq gc-cons-threshold (* 50 1000 1000))

(defun vt/display-startup-time ()
  (message "Emacs loaded in %s with %d garbage collections."
           (format "%.2f seconds"
                   (float-time
                     (time-subtract after-init-time before-init-time)))
           gcs-done))

(add-hook 'emacs-startup-hook #'vt/display-startup-time)

#+end_src

* Native compilation
#+begin_src emacs-lisp

;; Set the correct eln-cache
(add-to-list 'native-comp-eln-load-path (expand-file-name "eln-cache/" user-emacs-directory))

;; Silence compiler warnings as they can be pretty disruptive
(setq native-comp-async-report-warnings-errors nil)

#+end_src

* Package system setup
straight.el: next-generation, purely functional package manager for the Emacs hacker.

#+begin_src emacs-lisp

(setq straight-check-for-modifications '(check-on-save find-when-checking))
(setq straight-repository-branch "develop")
;; Bootstrap straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))


;; Use straight.el for use-package expressions
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

;; Load the helper package for commands like `straight-x-clean-unused-repos'
(require 'straight-x)

#+end_src

* Keep folders clean
We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

(use-package no-littering)

(setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

* Bootstrap
** Better Defaults
#+BEGIN_SRC emacs-lisp

(setq-default
 create-lockfiles nil            ; do not create lock files
 intent-tabs-mode nil            ; do not use hard tabs
 auto-save-default nil           ; do not auto save
 enable-recursive-minibuffers t  ; allow commands to be run on mini buffers
 auto-windows-vscroll nil        ; lighten vertical scroll
 delete-by-moving-to-trash t     ; delete files to trash
 fill-column 80                  ; set witdh for automatic line breaks
 help-window-select t            ; focus new help windows when opened
 show-trailing-whitespace nil    ; do not display trailing whitespaces
 tab-width 4                     ; set width for tabs
 )

(cd "~/")                           ; cd into home
(delete-selection-mode 1)           ; replace region when inserting text
(fset 'yes-or-no-p 'y-or-n-p)       ; replace yes/no prompts with y/n
(global-auto-revert-mode t)         ; automatically update buffers if file changes on disk
(column-number-mode t)              ; display column number in mode line
(setq backup-directory-alist '(("." . "~/.save")))
(setq echo-keystrokes 0.1)
(setq x-stretch-cursor t)

#+END_SRC

Disable startup message in favour of a org-mode scratch buffer
#+BEGIN_SRC emacs-lisp

(setq
 inhibit-splash-screen t
 initial-scratch-message nil
 initial-major-mode 'org-mode)

#+END_SRC

Add parts of each file's directory to the buffer if not unique
#+begin_src emacs-lisp

(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)

#+end_src

Pinentry
Emacs can be prompted for the PIN of GPG private keys, we just need to set epa-pinentry-mode to accomplish that
#+begin_src emacs-lisp

(use-package pinentry
  :init
  (pinentry-start)
  :config
  (setq epa-pinentry-mode 'loopback))

#+end_src

Save a list of recent files visited
#+begin_src emacs-lisp
(recentf-mode 1)
(defvar recentf-max-saved-items)
(setq recentf-max-saved-items 100)
#+end_src

** UI
This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.
#+begin_src emacs-lisp

(progn
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (scroll-bar-mode -1)
  (show-paren-mode 1))

#+end_src

Line numbers width
#+begin_src emacs-lisp

(setq display-line-numbers-width t)

#+end_src

Display time
#+begin_src emacs-lisp

(display-time-mode 1)

#+end_src

Scrolling
#+begin_src emacs-lisp

(setq scroll-conservatively 101)

#+end_src

Transparency
#+begin_src emacs-lisp

;; Set frame transparency
(set-frame-parameter (selected-frame) 'alpha vt/frame-transparency)
(add-to-list 'default-frame-alist `(alpha . ,vt/frame-transparency))

#+end_src

Control Buffer Placement
Emacs' default buffer placement algorithm is pretty disruptive if you like setting up window layouts a certain way in your workflow. The display-buffer-alist video controls this behavior and you can customize it to prevent Emacs from popping up new windows when you run commands. 
#+begin_src emacs-lisp

(setq org-src-window-setup 'split-window-right)
(setq display-buffer-alist
	  `(;; top side window
		("\\*Messages.*"
		 (display-buffer-in-side-window)
		 (window-height . 0.16)
		 (side . top)
		 (slot . 1))
		("\\*\\(Backtrace\\|Warnings\\|Flycheck errors\\|Compile-Log\\)\\*"
		 (display-buffer-in-side-window)
		 (window-height . 0.16)
		 (side . top)
		 (slot . 2)
		 (window-parameters . ((no-other-window . t))))
		;; bottom side window
		("\\*\\(Embark\\)?.*Completions.*"
		 (display-buffer-in-side-window)
		 (side . bottom)
		 (slot . 0)
		 (window-parameters . ((no-other-window . t)
							   (mode-line-format . none))))
		;; right side window
		("\\*Help.*"
		 (display-buffer-in-side-window)
		 (window-width . 0.4)			; See the :hook
		 (side . right)
		 (slot . 0))
		("\\*WoMan.*"
		 (display-buffer-in-side-window)
		 (window-width . 0.4)			; See the :hook
		 (side . right)
		 (slot . 1))
		("\\*Apropos\\*"
		 (display-buffer-in-side-window)
		 (window-width . 0.4)			; See the :hook
		 (side . right)
		 (slot . 2))
		;; bottom buffer (NOT side window)
		("\\*\\(Output\\|Register Preview\\).*"
		 (display-buffer-at-bottom))
		("\\*.*\\(e?shell\\|v?term\\).*"
		 (display-buffer-reuse-mode-window display-buffer-at-bottom)
		 (window-height . 0.2))
		;; below current window
		("\\*Calendar.*"
		 (display-buffer-reuse-mode-window display-buffer-below-selected)
		 (window-height . shrink-window-if-larger-than-buffer))))

#+end_src

Add fringe to buffer
#+BEGIN_SRC emacs-lisp

(set-fringe-mode 10)

#+END_SRC

Font - PragmataPro / Iosevka Aile
#+BEGIN_SRC emacs-lisp

(defun vt/set-font-faces ()
  (set-face-attribute 'default nil :font "PragmataPro Mono Liga" :height vt/default-font-size)
  (set-face-attribute 'fixed-pitch nil :font "PragmataPro Mono Liga" :height vt/default-font-size)
  (set-face-attribute 'variable-pitch nil :font "Iosevka Aile" :height vt/default-variable-font-size :weight 'regular))

(if (daemonp)
	(add-hook 'after-make-frame-functions
			  (lambda (frame)
				(setq doom-modeline-icon t)
				(with-selected-frame frame
				  (vt/set-font-faces))))
  (vt/set-font-faces))

#+END_SRC

All the icons
#+BEGIN_SRC emacs-lisp

(use-package all-the-icons)

#+END_SRC

Theme
[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x consult-theme= to choose between them easily.
#+BEGIN_SRC emacs-lisp

(use-package doom-themes
  :init (load-theme 'doom-gruvbox t)
  ;; :init (load-theme 'modus-operandi t)
  ;; :init (load-theme 'modus-vivendi t)
  (doom-themes-visual-bell-config))

(use-package humanoid-themes)

(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
(add-to-list 'default-frame-alist '(fullscreen . maximized))

#+END_SRC

** Custom functions
A collection of useful custom functions

*** Toggles
Functions to toggle various settings

#+begin_src emacs-lisp

(defun vt/toggle-line-numbers ()
  "Toggle line numbers in buffer"
  (interactive)
  (setq display-line-numbers
		(not (bound-and-true-p display-line-numbers))))

(defun vt/toggle-corfu-mode ()
  "Toggle corfu mode in buffer"
  (interactive)
  (if (bound-and-true-p corfu-mode)
	  (corfu-mode -1)
	(corfu-mode 1)))

#+end_src

*** Open files
Functions to open various important files

#+begin_src emacs-lisp

(defun vt/open-config-file ()
  "Load the literate config file for Emacs"
  (interactive)
  (find-file "~/emacs-configs/emacs-default/dotemacs.org"))

#+end_src

*** Secrets
#+begin_src emacs-lisp

(defun vt/load-secret (&optional name)
  "Read a Lisp structure from the secret file.
When NAME is provided, return the value associated to this key."
  (let ((file (expand-file-name ".secrets.eld")))
	(when (file-exists-p file)
	  (with-demoted-errors "Error while parsing secret file: %S"
		(with-temp-buffer
		  (insert-file-contents file)
		  (if-let ((content (read (buffer-string)))
				   (name))
			  (alist-get name content)
			content))))))

(defun vt/fetch-password (&rest params)
  (require 'auth-source)
  (let ((match (car (apply 'auth-source-search params))))
	(if match
		(let ((secret (plist-get match :secret)))
		  (if (functionp secret)
			  (funcall secret)
			secret))
	  (error "Password not found for %S" params))))

#+end_src

*** Icons
Variant functions to add icons.

#+begin_src emacs-lisp

(defun vt/with-faicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-faicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun vt/with-fileicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-fileicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun vt/with-octicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-octicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun vt/with-material (icon str &optional height v-adjust)
  (s-concat (all-the-icons-material icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

#+end_src

*** Github Review
#+begin_src emacs-lisp

(defun vt/start-github-review ()
  (interactive)
  (github-review-forge-pr-at-point))

#+end_src

*** Play with mpv
#+begin_src emacs-lisp

(defun vt/elfeed-play-with-mpv ()
  "Play entry link with mpv."
  (interactive)
  (let ((entry (if (eq major-mode 'elfeed-show-mode) elfeed-show-entry (elfeed-search-selected :single)))
        (quality-arg "")
        (quality-val (completing-read "Max height resolution (0 for unlimited): " '("0" "480" "720") nil nil)))
    (setq quality-val (string-to-number quality-val))
    (message "Opening %s with height≤%s with mpv..." (elfeed-entry-link entry) quality-val)
    (when (< 0 quality-val)
      (setq quality-arg (format "--ytdl-format=[height<=?%s]" quality-val)))
    (start-process "elfeed-mpv" nil "mpv" quality-arg (elfeed-entry-link entry))))

#+end_src

*** Open URL in mpv
#+begin_src emacs-lisp

(defun vt/open-with-mpv ()
  "Get URL at point and open it in mpv."
  (interactive)
  (when (org-in-regexp org-bracket-link-regexp 1)
	(let* ((url (org-link-unescape (org-match-string-no-properties 1)))
		   (quality-arg "")
		   (quality-val (completing-read "Max resolution (0 for unlimited): " '("0" "480" "720") nil nil)))
	  (if (not url)
		  (error "No url copied!")
		(setq quality-val (string-to-number quality-val))
		(message (concat "Opening: " url))
		(when (< 0 quality-val)
		  (setq quality-arg (format "--ytdl-format=[height<=?%s]" quality-val)))
		(start-process "org-mpv" nil "mpv" quality-arg url)))))

#+end_src

*** EWW
#+begin_src emacs-lisp

(defun vt/eww-rename-buffer ()
  "Rename EWW buffer using page title or URL."
  (let ((name (if (eq "" (plist-get eww-data :title))
				  (plist-get eww-data :url)
				(plist-get eww-data :title))))
	(rename-buffer (format "*%s # eww*" name) t)))

#+end_src

** Key bindings
This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

Make ESC quit prompts
#+BEGIN_SRC emacs-lisp

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+END_SRC

General
#+BEGIN_SRC emacs-lisp

(use-package general
  :config
  (general-create-definer vt/leader-keys
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "C-SPC")

  (vt/leader-keys
   "c" '(:ignore t :which-key "config")
   "cc" '(vt/open-config-file :which-key "open config")
   "t" '(:ignore t :which-key "toggles")
   "tl" '(vt/toggle-line-numbers :which-key "line numbers")
   "tc" '(vt/toggle-corfu-mode :which-key "corfu mode")
   "tt" '(consult-theme :which-key "choose theme")))

#+END_SRC

Hydra
#+BEGIN_SRC emacs-lisp

(use-package hydra
  :defer t)

(use-package pretty-hydra
  :straight t)

(pretty-hydra-define vt/hydra-text-scale
  (:title "Increase/decrease text size"
		  :quit-key "q"
		  :timeout 4)
  ("Scale text"
   (("j" text-scale-increase "in")
	("k" text-scale-decrease "out")
	("f" nil "finished" :exit t))))

(vt/leader-keys
  "ts" '(vt/hydra-text-scale/body :which-key "scale text"))

#+END_SRC

** Control buffer placement

#+begin_src emacs-lisp

(setq display-buffer-base-action
	  '(display-buffer-reuse-mode-window
		display-buffer-reuse-window
		display-buffer-same-window))

;; If a popup does happen, don't resize windows to be equal-sized
(setq even-window-sizes nil)

#+end_src

* Packages
** Selectrum
The focus of [[https://github.com/raxod502/selectrum][Selectrum]] is on providing an enhanced completion UI and compose with other packages which stay within the constraints of the standard Emacs API. Because of the modular approach there are several possible package combinations.

#+begin_src emacs-lisp

(use-package selectrum
  :straight t
  :disabled t
  :config
  (selectrum-mode +1)
  :custom
  (selectrum-extend-current-candidate-highlight t)
  (selectrum-fix-vertical-window-height t))

#+end_src

** Selectrum Prescient
[[https://github.com/raxod502/prescient.el][prescient.el]] is a library which sorts and filters lists of candidates, such as appear when you use a package like Ivy or Company. Extension packages such as ivy-prescient.el and company-prescient.el adapt the library for usage with various frameworks.

#+begin_src emacs-lisp

(use-package selectrum-prescient
  :after selectrum
  :disabled t
  :init
  (selectrum-prescient-mode +1)
  (prescient-persist-mode +1))

#+end_src

** Vertico
[[https://github.com/minad/vertico][Vertico]] provides a minimalistic vertical completion UI, which is based on the default completion system. By reusing the default system, Vertico achieves full compatibility with built-in Emacs commands and completion tables.

#+begin_src emacs-lisp

(use-package vertico
  :straight '(vertico :host github
					  :repo "minad/vertico"
					  :branch "main")
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))

#+end_src

** Save Hist
#+begin_src emacs-lisp

(use-package savehist
  :config
  (setq history-length 25)
  (savehist-mode 1))

#+end_src

** Consult
[[https://github.com/minad/consult][consult]] provides various practical commands based on the Emacs completion function completing-read, which allows to quickly select an item from a list of candidates with completion.

#+begin_src emacs-lisp

(use-package consult
  :straight t
  :bind (([remap list-buffers] . consult-buffer)
		 ("C-c h" . consult-history)
		 ("C-c m" . consult-mode-command)
		 ("C-c b" . consult-bookmark)
		 ("C-s" . consult-line)
		 ("C-x b" . consult-buffer)
		 ("M-y" . consult-yank-pop)
		 ("M-g g" . consult-goto-line)
		 ("M-g M-g" . consult-goto-line)
		 ("M-g o" . consult-outline)
		 ("M-g i" . consult-imenu)
		 ("M-g I" . consult-project-imenu)
		 ("M-s f" . consult-find)
		 ("M-s L" . consult-locate)
		 ("M-s G" . consult-git-grep)
		 ("M-s r" . consult-ripgrep)
		 ("M-s l" . consult-line)
		 ("M-s e" . consult-isearch)
		 :map isearch-mode-map
		 ("M-e" . consult-isearch)
		 ("M-s e" . consult-isearch)
		 ("M-s l" . consult-line))
  :init
  (setq xref-show-xrefs-function #'consult-xref
		xref-show-definitions-function #'consult-xref)
  :config
  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root))

(use-package consult-flycheck
  :bind (:map flycheck-command-map
			  ("!" . consult-flycheck)))

(vt/leader-keys
  "b" '(:ignore t :which-key "buffer")
  "bb" '(consult-buffer :which-key "list buffers")
  "bs" '(save-buffer :which-key "save buffer"))

#+end_src

** Orderless
This package provides an [[https://github.com/oantolin/orderless][orderless]] completion style that divides the pattern into space-separated components, and matches candidates that match all of the components in any order

#+begin_src emacs-lisp

(use-package orderless
  :straight t
  :init
  (setq completion-styles '(orderless)
		completion-category-defaults nil
		completion-category-overrides '((file (styles . (partial-completion))))))

#+end_src

** Embark
This package provides a sort of right-click contextual menu for Emacs, accessed through the [[https://github.com/oantolin/embark/][embark]]-act command (which you should bind to a convenient key), offering you relevant actions to use on a target determined by the context:

+ In the minibuffer, the target is the current best completion candidate.
+ In the *Completions* buffer the target is the completion at point.
+ In a regular buffer, the target is the region if active, or else the file, symbol or URL at point.

#+begin_src emacs-lisp

(use-package embark
  :straight t
  :bind
  (("C-S-a" . embark-act)	  ;; pick some comfortable binding
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
  :init
  (setq prefix-help-command #'embark-prefix-help-command))

(use-package embark-consult
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . embark-consult-preview-minor-mode))

#+end_src

** Marginalia
 [[https://github.com/minad/marginalia][Marginalia]] are marks or annotations placed at the margin of the page of a book or in this case helpful colorful annotations placed at the margin of the minibuffer for your completion candidates.

#+begin_src emacs-lisp

(use-package marginalia
  :after vertico
  :straight t
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
  :init
  (marginalia-mode))

#+end_src

** Doom modeline
[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs. The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.
#+BEGIN_SRC emacs-lisp

(use-package doom-modeline
  :custom-face
  (mode-line ((t (:height 0.9))))
  (mode-line-inactive ((t (:height 0.9))))
  :custom
  (doom-modeline-bar-width 3)
  (doom-modeline-height 32)
  (doom-modeline-buffer-file-name-style 'truncate-except-project)
  :init (doom-modeline-mode 1))

(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8, so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (unless (or (eq buffer-file-coding-system 'utf-8-unix)
                          (eq buffer-file-coding-system 'utf-8)))))

(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)

#+END_SRC

** Vim in emacs - evil mode
#+BEGIN_SRC emacs-lisp

(use-package evil
  :init
  (setq evil-want-keybinding nil)
  (setq evil-want-integration t)
  (setq evil-search-module 'evil-search)
  (setq evil-ex-complete-emacs-commands nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-shift-round nil)
  (setq evil-want-C-u-scroll t)
  :config
  (evil-mode 1))

;; Use visual line motions even outside of visual-line-mode buffers
(evil-global-set-key 'motion "j" 'evil-next-visual-line)
(evil-global-set-key 'motion "k" 'evil-previous-visual-line)

#+END_SRC

** Evil Collection
#+BEGIN_SRC emacs-lisp

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

(use-package evil-escape
  :after evil
  :config
  (setq evil-escape-excluded-states '(normal visual multiedit emacs motion))
  (setq-default evil-escape-key-sequence "jk"
                evil-escape-delay 0.15)
  (evil-escape-mode))

#+END_SRC

** Evil Nerd Commenter

Emacs' built in commenting functionality =comment-dwim= (usually bound to =M-;=) doesn't always comment things in the way you might expect so we use [[https://github.com/redguardtoo/evil-nerd-commenter][evil-nerd-commenter]] to provide a more familiar behavior.  I've bound it to =M-/= since other editors sometimes use this binding but you could also replace Emacs' =M-;= binding with this command.

#+begin_src emacs-lisp

(use-package evil-nerd-commenter
  :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

** Which Key
[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.
#+BEGIN_SRC emacs-lisp

(use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 0.3))

#+END_SRC

** Helpful
[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+BEGIN_SRC emacs-lisp

(use-package helpful
  :bind
  ([remap describe-function] . helpful-callable)
  ([remap describe-variable] . helpful-variable)
  ([remap describe-command] . helpful-command)
  ([remap describe-key] . helpful-key))

#+END_SRC

** Rainbow delimiters
#+BEGIN_SRC emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+END_SRC

** Projectile
#+BEGIN_SRC emacs-lisp

(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :demand t
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  (when (file-directory-p "~/code")
    (setq projectile-project-search-path '("~/code")))
  (setq projectile-switch-project-action #'projectile-dired))

(vt/leader-keys
  "p" '(:ignore t :which-key "projectile")
  "pp" '(projectile-switch-project :which-key "switch project")
  "pf" '(project-find-file :which-key "find project file")
  "sp" '(consult-ripgrep :which-key "search in project"))

#+END_SRC

** Magit
#+BEGIN_SRC emacs-lisp

(use-package magit
  :commands (magit-status magit-get-current-branch)
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))


(vt/leader-keys
  "g" '(:ignore t :which-key "magit")
  "gg" '(magit-status :which-key "magit status")
  "gb" '(magit-blame :which-key "magit blame"))

#+END_SRC

** Forge
#+BEGIN_SRC emacs-lisp

(use-package forge
  :after magit)

#+END_SRC

** Github Review
#+begin_src emacs-lisp

(use-package github-review
  :after magit
  :config
  (transient-append-suffix 'forge-dispatch "c u"
	'("c r" "Review pull request" vt/start-github-review)))

#+end_src

** Org Mode
[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

Font faces
#+BEGIN_SRC emacs-lisp

(defun vt/org-font-setup ()
  ;; Replace list hyphen with dot
  (font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

  ;; Set faces for heading levels
  (dolist (face '((org-level-1 . 1.2)
                  (org-level-2 . 1.1)
                  (org-level-3 . 1.05)
                  (org-level-4 . 1.0)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
                  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil :font "Iosevka Aile" :weight 'regular :height (cdr face)))

  ;; Ensure that anything that should be fixed-pitch in Org files appears that way
  (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))

#+END_SRC

Org mode configuration
#+BEGIN_SRC emacs-lisp

(defun vt/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (visual-line-mode 1))

(use-package org
  :commands (org-capture org-agenda)
  :hook (org-mode . vt/org-mode-setup)
  :bind (("C-x y" . vt/open-with-mpv))
  :config
  (setq org-ellipsis " ▾"
        org-hide-emphasis-markers t)
  (setq org-edit-src-content-indentation 2
        org-src-tab-acts-natively t
        org-src-preserve-indentation t)

  (setq org-fontify-done-headline t)
  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)

  (setq org-agenda-files (list "~/Documents/org"))

  (require 'org-habit)
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-graph-column 60)

  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

  (setq org-refile-targets
        '(("Archive.org" :maxlevel . 1)
          ("Tasks.org" :maxlevel . 1)))

  ;; Save Org buffers after refiling!
  (advice-add 'org-refile :after 'org-save-all-org-buffers)

  (setq org-tag-alist
        '((:startgroup)
                                        ; Put mutually exclusive tags here
          (:endgroup)
          ("@errand" . ?E)
          ("@home" . ?H)
          ("@work" . ?W)
          ("agenda" . ?a)
          ("planning" . ?p)
          ("publish" . ?P)
          ("batch" . ?b)
          ("note" . ?n)
          ("idea" . ?i)))

  (setq org-agenda-custom-commands
        '(("d" "Dashboard"
           ((agenda "" ((org-deadline-warning-days 7)))
            (todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))
            (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

          ("n" "Next Tasks"
           ((todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))))

          ("W" "Work Tasks" tags-todo "+work-email")

          ;; Low-effort next actions
          ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
           ((org-agenda-overriding-header "Low Effort Tasks")
            (org-agenda-max-todos 20)
            (org-agenda-files org-agenda-files)))

          ("w" "Workflow Status"
           ((todo "WAIT"
                  ((org-agenda-overriding-header "Waiting on External")
                   (org-agenda-files org-agenda-files)))
            (todo "REVIEW"
                  ((org-agenda-overriding-header "In Review")
                   (org-agenda-files org-agenda-files)))
            (todo "PLAN"
                  ((org-agenda-overriding-header "In Planning")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "BACKLOG"
                  ((org-agenda-overriding-header "Project Backlog")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "READY"
                  ((org-agenda-overriding-header "Ready for Work")
                   (org-agenda-files org-agenda-files)))
            (todo "ACTIVE"
                  ((org-agenda-overriding-header "Active Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "COMPLETED"
                  ((org-agenda-overriding-header "Completed Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "CANC"
                  ((org-agenda-overriding-header "Cancelled Projects")
                   (org-agenda-files org-agenda-files)))))))

  (setq org-capture-templates
        `(("t" "Tasks / Projects")
          ("tt" "Task" entry (file+olp "~/Documents/org/Tasks.org" "Inbox")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

          ("j" "Journal Entries")
          ("jj" "Journal" entry
           (file+olp+datetree "~/Documents/org/Journal.org")
           "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
           ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
           :clock-in :clock-resume
           :empty-lines 1)
          ("jm" "Meeting" entry
           (file+olp+datetree "~/Documents/org/Journal.org")
           "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
           :clock-in :clock-resume
           :empty-lines 1)

          ("w" "Workflows")
          ("we" "Checking Email" entry (file+olp+datetree "~/Documents/org/Journal.org")
           "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

          ("m" "Metrics Capture")
          ("mw" "Weight" table-line (file+headline "~/Documents/org/Metrics.org" "Weight")
           "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

  (define-key global-map (kbd "C-c j")
    (lambda () (interactive) (org-capture nil "jj")))

  (vt/org-font-setup))

(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode))

(defun vt/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . vt/org-mode-visual-fill))

#+END_SRC

** Org Appear
This package makes it much easier to edit Org documents when org-hide-emphasis-markers is turned on. It temporarily shows the emphasis markers around certain markup elements when you place your cursor inside of them. No more fumbling around with = and * characters! 

#+begin_src emacs-lisp

(use-package org-appear
  :hook (org-mode . org-appear-mode))

#+end_src

** Dired 
Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!
 
**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp

(use-package dired
  :ensure nil
  :straight nil
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :custom ((dired-listing-switches "-agho --group-directories-first"))
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
    "h" 'dired-single-up-directory
    "l" 'dired-single-buffer))

(use-package dired-single
  :after dired)

(use-package all-the-icons-dired
  :hook (dired-mode . all-the-icons-dired-mode))

(use-package dired-open
  :config
  ;; Doesn't work as expected!
  ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
  (setq dired-open-extensions '(("png" . "feh")
                                ("mkv" . "mpv"))))

(vt/leader-keys
  "d" '(:ignore t :which-key "dired")
  "dj" '(dired-jump :which-key "jump to folder"))

;; (use-package dired-hide-dotfiles
;;   :hook (dired-mode . dired-hide-dotfiles-mode)
;;   :config
;;   (evil-collection-define-key 'normal 'dired-mode-map
;;     "H" 'dired-hide-dotfiles-mode))

#+end_src

** Eshell
[[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Contributors-to-Eshell][Eshell]] is Emacs' own shell implementation written in Emacs Lisp.  It provides you with a cross-platform implementation (even on Windows!) of the common GNU utilities you would find on Linux and macOS (=ls=, =rm=, =mv=, =grep=, etc).  It also allows you to call Emacs Lisp functions directly from the shell and you can even set up aliases (like aliasing =vim= to =find-file=).  Eshell is also an Emacs Lisp REPL which allows you to evaluate full expressions at the shell.

The downsides to Eshell are that it can be harder to configure than other packages due to the particularity of where you need to set some options for them to go into effect, the lack of shell completions (by default) for some useful things like Git commands, and that REPL programs sometimes don't work as well.  However, many of these limitations can be dealt with by good configuration and installing external packages, so don't let that discourage you from trying it!

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor

We will be covering Eshell more in future videos highlighting other things you can do with it.

For more thoughts on Eshell, check out these articles by Pierre Neidhardt:
- https://ambrevar.xyz/emacs-eshell/index.html
- https://ambrevar.xyz/emacs-eshell-versus-shell/index.html
  
#+begin_src emacs-lisp

(defun vt/configure-eshell ()
  ;; Save command history when commands are entered
  (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

  ;; Truncate buffer for performance
  (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

  ;; Bind some useful keys for evil-mode
  (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
  (evil-normalize-keymaps)

  (setq eshell-history-size         10000
        eshell-buffer-maximum-lines 10000
        eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t))

(use-package eshell-git-prompt
  :after eshell)

(use-package eshell
  :hook (eshell-first-time-mode . vt/configure-eshell)
  :config

  (with-eval-after-load 'esh-opt
    (setq eshell-destroy-buffer-when-process-dies t)
    (setq eshell-visual-commands '("htop" "zsh" "vim")))

  (eshell-git-prompt-use-theme 'powerline))


#+end_src

** Emoji
Emojify is an Emacs extension to display emojis. It can display github style emojis like :smile: or plain ascii ones like :). It tries to be as efficient as possible, while also providing a lot of flexibility.
#+begin_src emacs-lisp

(use-package emojify
  :hook (after-init . global-emojify-mode))

#+end_src

** Elfeed
An RSS newsfeed reader for Emacs.

#+begin_src emacs-lisp

(use-package elfeed
  :after evil
  :commands elfeed
  :bind (
		 :map elfeed-search-mode-map
			  ("C-x y" . vt/elfeed-play-with-mpv))
  :config
  (setq elfeed-search-feed-face ":foreground #ff0000 :weight bold")
  (setq-default elfeed-search-filter "@1-week-ago +unread "))

(use-package elfeed-org
  :after elfeed
  :config (setq rmh-elfeed-org-files (list "~/emacs-configs/emacs-default/elfeed.org"))
  :init
  (elfeed-org))

(use-package elfeed-goodies
  :after elfeed
  :init
  (elfeed-goodies/setup))

#+end_src

** Lispy 
Here are packages that are useful across different Lisp and Scheme implementations: 

#+begin_src emacs-lisp

(use-package lispy
  :hook ((emacs-lisp-mode . lispy-mode)
         (scheme-mode . lispy-mode)))

(use-package lispyville
  :hook ((lispy-mode . lispyville-mode))
  :config
  (lispyville-set-key-theme '(operators c-w additional
										additional-movement slurp/barf-cp
										prettify)))

#+end_src

** Smart Parens
#+begin_src emacs-lisp

(use-package smartparens
  :hook (prog-mode . smartparens-mode))

#+end_src

** Avy
[[https://github.com/abo-abo/avy][avy]] is a GNU Emacs package for jumping to visible text using a char-based decision tree.

#+begin_src emacs-lisp

(use-package avy
  :commands (avy-goto-char avy-goto-word-0 avy-goto-line))

(vt/leader-keys
  "j" '(:ignore t :which-key "jump")
  "jj" '(avy-goto-char :which-key "jump to char")
  "jw" '(avy-goto-word-0 :which-key "jump to word")
  "jl" '(avy-goto-line :which-key "jump to line"))

#+end_src

** Dashboard
An extensible emacs startup screen showing you what’s most important.

#+begin_src emacs-lisp

(use-package dashboard
  :disabled t
  :init
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Welcome Vlad!")
  (setq dashboard-center-content nil)
  (setq dashboard-items '((recents . 5)
						  (agenda . 5)
						  (bookmarks . 3)
						  (projects . 3)
						  (registers . 3)))
  :config
  (dashboard-setup-startup-hook))

;; (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))

#+end_src

** Spotify
Control [[https://github.com/danielfm/smudge][Spotify]] clients from within Emacs.

#+begin_src emacs-lisp

(use-package smudge
  :commands smudge-controller-toggle-play
  :custom
  (smudge-oauth2-client-id (vt/load-secret 'spotify-id))
  (smudge-oauth2-client-secret (vt/load-secret 'spotify-secret)))

(pretty-hydra-define vt/hydra-spotify
  (:title (vt/with-faicon "spotify" "Spotify" 1 -0.05))
  ("Search"
   (("t" smudge-track-search "Track" :exit t)
	("m" smudge-my-playlists "My Playlists" :exit t)
	("f" smudge-featured-playlists "Featured Playlists" :exit t)
	("u" smudge-user-playlists "User Playlists" :exit t)
	("l" smudge-playlist-search "Search Playlist" :exit t))
   "Control"
   (
	("SPC" smudge-controller-toggle-play "Play/Pause" :exit nil)
	("n" smudge-controller-next-track "Next Track" :exit nil)
	("p" smudge-controller-previous-track "Previous Track" :exit nil)
	("r" smudge-controller-toggle-repeat "Repeat" :exit nil)
	("s" smudge-controller-toggle-shuffle "Shuffle" :exit nil))
   "Manage"
   (
	("+" smudge-controller-volume-up "Volume up" :exit nil)
	("-" smudge-controller-volume-down "Volume down" :exit nil)
	("x" smudge-controller-volume-mute-unmute "Mute" :exit nil)
	("d" smudge-select-device "Select Device" :exit nil)
	("f" nil "quit" :exit t))))

(vt/leader-keys
  "m" '(vt/hydra-spotify/body :which-key "spotify"))

#+end_src

** EWW
Eww (the Eacs Web Wowser) is a Web browser written in elisp and based on shr.el.

#+begin_src emacs-lisp

(setq shr-use-fonts nil
	  shr-cookie-policy nil
	  shr-discard-aria-hidden t
	  shr-image-animate nil)

(use-package eww
  :config
  (setq browse-url-browser-function 'eww-browse-url
		eww-search-prefix "https://duckduckgo.com/html?q="))

(add-hook 'eww-after-render-hook #'vt/eww-rename-buffer)
(advice-add 'eww-back-url :after #'vt/eww-rename-buffer)
(advice-add 'eww-forward-url :after #'vt/eww-rename-buffer)

#+end_src

** Sly
#+begin_src emacs-lisp

(use-package sly
  :straight t
  :config
  (setq org-babel-lisp-eval-fn #'sly-eval)
  (setq inferior-lisp-program "/usr/bin/clisp"))

(use-package slime
  :straight t)

#+end_src

** Circe
[[https://github.com/jorgenschaefer/circe][Circe]] is a Client for IRC in Emacs. It tries to have sane defaults, and integrates well with the rest of the editor, using standard Emacs key bindings and indicating activity in channels in the status bar so it stays out of your way unless you want to use it.

#+begin_src emacs-lisp

(defun vt/circe-nickserv-password (server)
  (vt/fetch-password :login "nerevarine" :machine "irc.libera.chat"))

(use-package circe
  :init
  (enable-circe-color-nicks)
  :custom
  (setq circe-default-nick (vt/load-secret 'circe-nick)
		circe-default-realname (vt/load-secret 'circe-nick)
		circe-reduce-lurker-spam t
		circe-network-options
		'(("Libera Chat"
		   :tls t
		   :nickserv-password (vt/load-secret 'circe-pass)
		   :nickserv-identify-challenge (format "\C-b/msg\\s-NickServ\\s-identify\\s-<%S>\C-b" (vt/load-secret 'circe-pass))
		   :nickserv-identify-command (format "PRIVMSG NickServ :IDENTIFY {%s} {%s}" (vt/load-secret 'circe-nick) (vt/load-secret 'circe-pass))
		   :nickserv-identify-confirmation "^You are now identified for .*\\.$"
		   :channels (:after-auth "#emacs"))
		  )))

#+end_src

* Utilities
Setup org babel

#+BEGIN_SRC emacs-lisp

(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
	 (lisp . t)
	 (js . t)
	 (python . t)))

  (setq org-confirm-babel-evaluate nil)
  (push '("conf-unix" . conf-unix) org-src-lang-modes))

(with-eval-after-load 'org
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("js" . "src js"))
  (add-to-list 'org-structure-template-alist '("lp" . "src lisp")))

#+END_SRC

Auto tangle  config file
#+begin_src emacs-lisp

;; Automatically tangle our Emacs.org config file when we save it
(defun vt/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "dotemacs.org" user-emacs-directory))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'vt/org-babel-tangle-config)))

#+end_src

* Development
** IDE Features with lsp-mode
*** lsp-mode
We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp

(use-package lsp-mode
  :straight t
  :commands (lsp lsp-deferred)
  :hook ((typescript-mode js2-mode web-mode) . lsp)
  :init
  (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
  :custom (lsp-headerline-breadcrumb-enable nil)
  :config
  (lsp-enable-which-key-integration t))

#+end_src

*** lsp-ui
[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'bottom))

#+end_src

*** Autocomplete
[[https://github.com/minad/corfu][Corfu]] enhances the default completion in region function with a completion overlay. The current candidates are shown in a popup below or above the point. Corfu can be considered the minimalistic completion-in-region counterpart of the Vertico minibuffer UI.

#+begin_src emacs-lisp

(use-package corfu
  :straight '(corfu :host github
					:repo "minad/corfu"
					:branch "main")
  :bind (:map corfu-map
			  ("TAB" . corfu-next)
			  ("<backtab>" . corfu-previous))
  :custom
  (corfu-cycle t)
  :hook ((prog-mode . corfu-mode)
		 (shell-mode . corfu-mode)
		 (org-mode . corfu-mode)
		 (sly-mode . corfu-mode)
		 (eshell-mode . corfu-mode))
  :config
  (corfu-global-mode))

#+end_src

*** Tree Sitter
The minor mode tree-sitter-mode provides a buffer-local syntax tree, which is kept up-to-date with changes to the buffer’s text.

#+begin_src emacs-lisp

(use-package tree-sitter
  :after evil
  :init (global-tree-sitter-mode)
  :hook (tree-sitter-after-on-hook . tree-sitter-hl-mode))

(use-package tree-sitter-langs
  :after evil tree-sitter
  :config
  (tree-sitter-require 'tsx)
  (add-to-list 'tree-sitter-major-mode-language-alist '(typescript-tsx-mode . tsx)))

#+end_src

*** Flycheck
Syntax checking with Flycheck

#+begin_src emacs-lisp

(use-package flycheck
  :after lsp
  :hook (lsp-mode . flycheck-mode))

(vt/leader-keys
  "c" '(:ignore t :which-key "code")
  "ca" '(lsp-execute-code-action :which-key "code action")
  "cx" '(consult-flycheck :which-key "flycheck info"))
 
#+end_src

*** Editorconfig
[[https://github.com/editorconfig/editorconfig-emacs][Editorconfig]]
#+begin_src emacs-lisp

(use-package editorconfig
  :straight t
  :config
  (editorconfig-mode 1))

#+end_src

** Languages
*** TypeScript
This is a basic configuration for the TypeScript language so that =.ts or .tsx= files activate =typescript-mode= when opened. We're also adding a hook to =typescript-mode-hook= to call =lsp-deferred= so that we activate =lsp-mode= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp

(use-package typescript-mode
  :hook ((typescript-mode . lsp-deferred)
		 (typescript-mode . rainbow-delimiters-mode)
		 (typescript-mode . tree-sitter-hl-mode))
  :config
  (setq typescript-indent-level 2))

#+end_src

*** JavaScript
Inspired from Doom Emacs

#+begin_src emacs-lisp

(defun vt/set-js-indentation ()
  (setq js-indent-level 2)
  (setq evil-shift-width js-indent-level)
  (setq-default tab-width 2))

(use-package js2-mode
  :mode "\\.[mc]?js\\'"
  :mode "\\.es6\\'"
  :interpreter "node"
  :commands js2-line-break
  :config
  (setq js-chain-indent t
		;; Don't mishighlight shebang lines
		js2-skip-preprocessor-directives t
		;; let flycheck handle this
		js2-mode-show-parse-errors nil
		js2-mode-show-strict-warnings nil
		;; Flycheck provides these features, so disable them: conflicting with
		;; the eslint settings.
		js2-strict-trailing-comma-warning nil
		js2-strict-missing-semi-warning nil
		;; maximum fontification
		js2-highlight-level 3
		js2-highlight-external-variables t
		js2-idle-timer-delay 0.1)

  (add-hook 'js2-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'js2-mode-hook #'vt/set-js-indentation))

(use-package apheleia
  :config
  (apheleia-global-mode 1))

(use-package prettier-js
  ;; :hook ((js2-mode . prettier-js-mode)
  ;;        (typescript-mode . prettier-js-mode))
  :config
  (setq prettier-js-show-errors nil))


#+end_src

*** Typescript-tsx
#+begin_src emacs-lisp

(progn
  (define-derived-mode typescript-tsx-mode web-mode "TypeScript-tsx")
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-tsx-mode)))
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))

#+end_src

*** Web
#+begin_src emacs-lisp

(use-package web-mode
  :mode "(\\.\\(html?\\|ejs\\|tsx\\|jsx\\)\\'"
  :config
  (setq-default web-mode-code-indent-offset 2)
  (setq-default web-mode-markup-indent-offset 2)
  (setq-default web-mode-attribute-indent-offset 2))

#+end_src

*** JSON
Major mode for editing [[https://github.com/joshwnj/json-mode][JSON]] files.

#+begin_src emacs-lisp

(use-package json-mode
  :straight t
  :config
  (setq json-reformat:indent-width 2))


#+end_src

* Runtime performance
Dial the GC threshold back down so that garbage collection happens more frequently but in less time.

#+begin_src emacs-lisp

;; Make gc pauses faster by decreasing the threshold.
(setq gc-cons-threshold (* 2 1000 1000))

#+end_src

